# Generated by Django 5.2.5 on 2025-09-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'Usuário Comum'), ('admin', 'Administrador'), ('superadmin', 'Super Administrador')], default='user', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
