# Generated by Django 5.2.6 on 2025-09-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dark_theme',
            field=models.BooleanField(default=False, verbose_name='Tema escuro'),
        ),
    ]
