# Generated by Django 5.2.4 on 2025-09-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0002_alter_blogpost_category'),
        ('site_management', '0002_create_default_site'),
    ]

    operations = [
    ]
