# Generated by Django 5.2.5 on 2025-09-11 20:45

from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0006_siteapikey'),
    ]

    def add_link_field(apps, schema_editor):
        # Evita erro se a coluna já existe no banco
        with connection.cursor() as cursor:
            cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name='site_management_service' AND column_name='link';")
            if cursor.fetchone():
                return  # Já existe
        # Se não existe, adiciona via SQL direto (fallback)
        schema_editor.execute("ALTER TABLE site_management_service ADD COLUMN link varchar(255) NULL;")

    operations = [
        migrations.RunPython(add_link_field, migrations.RunPython.noop),
    ]
