# Generated by Django 5.2.6 on 2025-09-12 00:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('suspended', 'Suspenso'), ('expired', 'Expirado')], default='active', max_length=20, verbose_name='Status')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Função do Usuário',
                'verbose_name_plural': 'Funções dos Usuários',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('permission_type', models.CharField(choices=[('create', 'Criar'), ('read', 'Visualizar'), ('update', 'Editar'), ('delete', 'Excluir'), ('manage', 'Gerenciar'), ('admin', 'Administrar')], default='read', max_length=20, verbose_name='Tipo de Permissão')),
                ('resource', models.CharField(max_length=100, verbose_name='Recurso')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='Categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'ordering': ['category', 'resource', 'permission_type'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('role_type', models.CharField(choices=[('system', 'Sistema'), ('account', 'Conta'), ('custom', 'Personalizada')], default='custom', max_length=20, verbose_name='Tipo de Função')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Prioridade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_system', models.BooleanField(default=False, verbose_name='Função do Sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.account', verbose_name='Conta')),
                ('parent_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_roles', to='permissions.role', verbose_name='Função Pai')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='Condições')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.permission', verbose_name='Permissão')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.role', verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Permissão da Função',
                'verbose_name_plural': 'Permissões das Funções',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='permissions.RolePermission', to='permissions.permission', verbose_name='Permissões'),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grant_type', models.CharField(choices=[('grant', 'Conceder'), ('deny', 'Negar')], default='grant', max_length=10, verbose_name='Tipo de Concessão')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='Condições')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='accounts.account', verbose_name='Conta')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Permissão do Usuário',
                'verbose_name_plural': 'Permissões dos Usuários',
                'ordering': ['-created_at'],
            },
        ),
    ]
