# Generated by Django 5.2.5 on 2025-09-02 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Concedido por'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='permissions.permission', verbose_name='Permissão'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.account', verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído por'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='permissions.role', verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['codename'], name='permissions_codenam_0251e1_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['resource'], name='permissions_resourc_295b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['category'], name='permissions_categor_e13fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['permission_type'], name='permissions_permiss_da3fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'is_active'], name='permissions_role_id_f3c8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission', 'is_active'], name='permissions_permiss_da93ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['codename'], name='permissions_codenam_4c4599_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['role_type'], name='permissions_role_ty_b3b6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['account'], name='permissions_account_959a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['priority'], name='permissions_priorit_3b599d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'account')},
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'is_active'], name='permissions_user_id_e85efd_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission', 'is_active'], name='permissions_permiss_35d259_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['account', 'is_active'], name='permissions_account_41ab9c_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['content_type', 'object_id'], name='permissions_content_a48310_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['valid_from', 'valid_until'], name='permissions_valid_f_870cfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission', 'account', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'status'], name='permissions_user_id_70c5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'status'], name='permissions_role_id_04b6e9_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['account', 'status'], name='permissions_account_3a8e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['valid_from', 'valid_until'], name='permissions_valid_f_ab8dcc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'account')},
        ),
    ]
