# Generated by Django 5.2.6 on 2025-09-12 00:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(message='Digite um CNPJ válido (XX.XXX.XXX/XXXX-XX)', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Digite um CPF válido (XXX.XXX.XXX-XX)', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('plan', models.CharField(choices=[('free', 'Gratuito'), ('basic', 'Básico'), ('premium', 'Premium'), ('enterprise', 'Empresarial')], default='free', max_length=20, verbose_name='Plano')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('suspended', 'Suspenso'), ('cancelled', 'Cancelado'), ('trial', 'Trial')], default='trial', max_length=20, verbose_name='Status')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Máximo de Usuários')),
                ('max_storage_gb', models.PositiveIntegerField(default=1, verbose_name='Armazenamento (GB)')),
                ('max_domains', models.PositiveIntegerField(default=1, verbose_name='Máximo de Domínios')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50, verbose_name='Fuso Horário')),
                ('language', models.CharField(default='pt-br', max_length=10, verbose_name='Idioma')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Trial Termina em')),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Assinatura Termina em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('manager', 'Gerente'), ('member', 'Membro'), ('viewer', 'Visualizador')], default='member', max_length=20, verbose_name='Função')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('declined', 'Recusado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('can_invite_users', models.BooleanField(default=False, verbose_name='Pode Convidar Usuários')),
                ('can_manage_billing', models.BooleanField(default=False, verbose_name='Pode Gerenciar Cobrança')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='Pode Gerenciar Configurações')),
                ('can_view_analytics', models.BooleanField(default=True, verbose_name='Pode Ver Análises')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Convite de Conta',
                'verbose_name_plural': 'Convites de Conta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('manager', 'Gerente'), ('member', 'Membro'), ('viewer', 'Visualizador')], default='member', max_length=20, verbose_name='Função')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('pending', 'Pendente'), ('suspended', 'Suspenso')], default='pending', max_length=20, verbose_name='Status')),
                ('can_invite_users', models.BooleanField(default=False, verbose_name='Pode Convidar Usuários')),
                ('can_manage_billing', models.BooleanField(default=False, verbose_name='Pode Gerenciar Cobrança')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='Pode Gerenciar Configurações')),
                ('can_view_analytics', models.BooleanField(default=True, verbose_name='Pode Ver Análises')),
                ('invited_at', models.DateTimeField(blank=True, null=True, verbose_name='Convidado em')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Entrou em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Membro da Conta',
                'verbose_name_plural': 'Membros da Conta',
                'ordering': ['-created_at'],
            },
        ),
    ]
