# Generated by Django 5.2.6 on 2025-09-12 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='accountinvitation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.account', verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='accountinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_account_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Convidado por'),
        ),
        migrations.AddField(
            model_name='accountmembership',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.account', verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='accountmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Convidado por'),
        ),
        migrations.AddField(
            model_name='accountmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['slug'], name='accounts_ac_slug_414a43_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['status'], name='accounts_ac_status_07de41_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['plan'], name='accounts_ac_plan_22f7da_idx'),
        ),
        migrations.AddIndex(
            model_name='accountinvitation',
            index=models.Index(fields=['token'], name='accounts_ac_token_ccabc5_idx'),
        ),
        migrations.AddIndex(
            model_name='accountinvitation',
            index=models.Index(fields=['email'], name='accounts_ac_email_43b0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='accountinvitation',
            index=models.Index(fields=['status'], name='accounts_ac_status_c6cc11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountinvitation',
            unique_together={('account', 'email')},
        ),
        migrations.AddIndex(
            model_name='accountmembership',
            index=models.Index(fields=['account', 'status'], name='accounts_ac_account_fefe49_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmembership',
            index=models.Index(fields=['user', 'status'], name='accounts_ac_user_id_f9b668_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmembership',
            index=models.Index(fields=['role'], name='accounts_ac_role_e18d9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountmembership',
            unique_together={('account', 'user')},
        ),
    ]
