# Generated by Django 5.2.4 on 2025-09-03 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='account',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(message='Digite um CNPJ válido (XX.XXX.XXX/XXXX-XX)', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='account',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Digite um CPF válido (XXX.XXX.XXX-XX)', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
    ]
