# Generated by Django 5.2.4 on 2025-09-03 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Chave única da configuração', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Valor da configuração')),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('text', 'Text')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descrição da configuração')),
                ('category', models.CharField(blank=True, help_text='Categoria da configuração', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='Se a configuração pode ser acessada publicamente')),
                ('is_editable', models.BooleanField(default=True, help_text='Se a configuração pode ser editada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
                'db_table': 'settings_global',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SettingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Chave da configuração', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nome amigável da configuração', max_length=200)),
                ('description', models.TextField(help_text='Descrição da configuração')),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('text', 'Text')], default='string', max_length=20)),
                ('default_value', models.TextField(blank=True, help_text='Valor padrão')),
                ('category', models.CharField(help_text='Categoria da configuração', max_length=50)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('account', 'Conta'), ('user', 'Usuário')], help_text='Escopo da configuração', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Se a configuração é obrigatória')),
                ('is_public', models.BooleanField(default=False, help_text='Se pode ser acessada publicamente')),
                ('validation_rules', models.JSONField(blank=True, help_text='Regras de validação em JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Configuração',
                'verbose_name_plural': 'Templates de Configurações',
                'db_table': 'settings_template',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Chave da configuração', max_length=100)),
                ('value', models.TextField(help_text='Valor da configuração')),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('text', 'Text')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descrição da configuração')),
                ('category', models.CharField(blank=True, help_text='Categoria da configuração', max_length=50)),
                ('is_inherited', models.BooleanField(default=False, help_text='Se herda valor da configuração global')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Configuração da Conta',
                'verbose_name_plural': 'Configurações das Contas',
                'db_table': 'settings_account',
                'ordering': ['account', 'category', 'key'],
                'unique_together': {('account', 'key')},
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Chave da configuração', max_length=100)),
                ('value', models.TextField(help_text='Valor da configuração')),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON'), ('text', 'Text')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descrição da configuração')),
                ('category', models.CharField(blank=True, help_text='Categoria da configuração', max_length=50)),
                ('is_inherited', models.BooleanField(default=False, help_text='Se herda valor da configuração da conta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração do Usuário',
                'verbose_name_plural': 'Configurações dos Usuários',
                'db_table': 'settings_user',
                'ordering': ['user', 'category', 'key'],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
