# Generated by Django 5.2.4 on 2025-09-03 12:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do domínio (ex: exemplo.com)', max_length=255, validators=[django.core.validators.RegexValidator(message='Digite um domínio válido (ex: exemplo.com)', regex='^[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?\\.[a-zA-Z]{2,}$')])),
                ('domain_type', models.CharField(choices=[('primary', 'Principal'), ('subdomain', 'Subdomínio'), ('custom', 'Personalizado')], default='custom', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('verified', 'Verificado'), ('failed', 'Falhou'), ('expired', 'Expirado')], default='pending', max_length=20)),
                ('verification_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('verification_method', models.CharField(choices=[('dns_txt', 'DNS TXT Record'), ('dns_cname', 'DNS CNAME Record'), ('file_upload', 'File Upload')], default='dns_txt', max_length=20)),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_certificate', models.TextField(blank=True, help_text='Certificado SSL')),
                ('ssl_private_key', models.TextField(blank=True, help_text='Chave privada SSL')),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('redirect_to', models.URLField(blank=True, help_text='URL para redirecionamento')),
                ('redirect_type', models.CharField(blank=True, choices=[('301', 'Permanente (301)'), ('302', 'Temporário (302)')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Domínio principal da conta')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='accounts.account')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DomainConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_enabled', models.BooleanField(default=True)),
                ('cache_ttl', models.PositiveIntegerField(default=3600, help_text='TTL do cache em segundos')),
                ('default_title', models.CharField(blank=True, max_length=60)),
                ('default_description', models.CharField(blank=True, max_length=160)),
                ('robots_txt', models.TextField(blank=True, help_text='Conteúdo do robots.txt')),
                ('google_analytics_id', models.CharField(blank=True, max_length=20)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=20)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=20)),
                ('force_https', models.BooleanField(default=True)),
                ('hsts_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='domains.domain')),
            ],
        ),
        migrations.CreateModel(
            name='DomainVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_method', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='domains.domain')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['account', 'status'], name='domains_dom_account_b872c4_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['status', 'is_active'], name='domains_dom_status_16cfa0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('name', 'account')},
        ),
    ]
