# Generated by Django 5.2.4 on 2025-09-03 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('slug', 'account')},
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('content_type', models.CharField(choices=[('article', 'Artigo'), ('page', 'Página'), ('post', 'Post'), ('news', 'Notícia'), ('product', 'Produto')], default='article', max_length=20)),
                ('excerpt', models.TextField(blank=True, help_text='Resumo do conteúdo', max_length=500)),
                ('content', models.TextField(help_text='Conteúdo principal')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='content/images/')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Destacar este conteúdo')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Título para SEO (máx. 60 caracteres)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Descrição para SEO (máx. 160 caracteres)', max_length=160)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='content/attachments/')),
                ('file_type', models.CharField(choices=[('image', 'Imagem'), ('document', 'Documento'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('other', 'Outro')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(help_text='Tamanho do arquivo em bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.content')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('slug', 'account')},
            },
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content.tag'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', 'published_at'], name='content_con_status_4e029e_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['account', 'status'], name='content_con_account_932ead_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['category', 'status'], name='content_con_categor_3393f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('slug', 'account')},
        ),
    ]
