# Generated by Django 5.2.6 on 2025-09-12 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category'),
        ),
        migrations.AddField(
            model_name='contentattachment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.content'),
        ),
        migrations.AddField(
            model_name='tag',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('slug', 'account')},
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['status', 'published_at'], name='content_con_status_4e029e_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['account', 'status'], name='content_con_account_932ead_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['category', 'status'], name='content_con_categor_3393f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('slug', 'account')},
        ),
    ]
