# Generated by Django 5.2.4 on 2025-09-03 13:07

import django.db.models.deletion
import uploads.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=uploads.models.upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Imagem'), ('document', 'Documento'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('other', 'Outro')], max_length=20)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='accounts.account')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploads_file',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageThumbnail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('small', 'Pequeno (150x150)'), ('medium', 'Médio (300x300)'), ('large', 'Grande (600x600)')], max_length=10)),
                ('file', models.ImageField(upload_to='thumbnails/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='uploads.uploadedfile')),
            ],
            options={
                'db_table': 'uploads_thumbnail',
            },
        ),
        migrations.CreateModel(
            name='UploadQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_storage_mb', models.PositiveIntegerField(default=1000)),
                ('max_file_size_mb', models.PositiveIntegerField(default=10)),
                ('max_files_per_month', models.PositiveIntegerField(default=100)),
                ('used_storage_bytes', models.BigIntegerField(default=0)),
                ('files_uploaded_this_month', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_quota', to='accounts.account')),
            ],
            options={
                'db_table': 'uploads_quota',
            },
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['account', 'file_type'], name='uploads_fil_account_9fbb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['uploaded_by'], name='uploads_fil_uploade_671860_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['created_at'], name='uploads_fil_created_cd8540_idx'),
        ),
        migrations.AddIndex(
            model_name='imagethumbnail',
            index=models.Index(fields=['original_file', 'size'], name='uploads_thu_origina_4aa17f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagethumbnail',
            unique_together={('original_file', 'size')},
        ),
    ]
