# Generated by Django 5.2.6 on 2025-09-12 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagethumbnail',
            name='original_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='uploads.uploadedfile'),
        ),
        migrations.AddField(
            model_name='uploadquota',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_quota', to='accounts.account'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['account', 'file_type'], name='uploads_fil_account_9fbb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['uploaded_by'], name='uploads_fil_uploade_671860_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['created_at'], name='uploads_fil_created_cd8540_idx'),
        ),
        migrations.AddIndex(
            model_name='imagethumbnail',
            index=models.Index(fields=['original_file', 'size'], name='uploads_thu_origina_4aa17f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagethumbnail',
            unique_together={('original_file', 'size')},
        ),
    ]
